### ISSUE TITLE
hook to capture client email for mailing list

### ISSUE THREAD

**Issue by orionrush** [Ecwid/ecwid-wordpress-plugin#104]
Helllo all

I'd like to capture the purchaser's email address and do a custom integration with my mailing list provider. 

* Ideally I'd like to add a custom opt-in checkbox for the mailing list on the sales confirmation page. 

* Alternatively, if I can capture the name, email address and a few relevant address fields on the completion of a sale, I could prepopulate a form and use your "Custom Redirect for 'Thank You' Page" App to have an optional newsletter signup form pre-populated on the redirect page. 

I've poured over the plugin source code, but I'm not seeing any obvious hooks for these purposes. 

Many thanks

**Comment by riq363** [comment]
Hi there!

Here are two ways to get the customer's permission and info for newsletters: 

1. You can use the built-in sign up box on the shopping cart page. If a customer agrees to receive newsletters, you will see "Promo emails allowed" next to this customer in Ecwid > My Sales > Customers.

More about this feature here: https://support.ecwid.com/hc/en-us/articles/360003704479

Customer's preference can be retrieved via REST API (see acceptMarketing field) after the order was placed:
* Search orders: https://developers.ecwid.com/api-documentation/orders
* Search customers: https://developers.ecwid.com/api-documentation/customers

Use webhooks to listen for changes in orders and customers: https://developers.ecwid.com/api-documentation/webhooks

2. If you'd like to use your own sign up form, you don't need to enable this native option. Instead, you can use Ecwid JS API. 

Create a JS code that will subscribe to OnOrderPlaced event. It will get name, email, address, and other details. Here's a link to our JS API documentation: https://developers.ecwid.com/api-documentation/subscribe-to-events#ecwid-onorderplaced

When an order has just been placed, you can use this information to redirect customer to a custom form filled out with the order details.

You can write custom JS on the same page where your store is located. Or you can load custom JS code wherever your store is embedded: https://developers.ecwid.com/api-documentation/customize-behaviour#add-custom-javascript-code

Thanks!

**Comment by orionrush** [comment]
@riq369 thanks for the very detailed response, there’s a lot for me to go on here - thank you!

**Comment by riq363** [comment]
Hey @orionrush sure thing! Feel free to reach out to us via https://developers.ecwid.com/contact or our support team if you have further questions.
