### ISSUE TITLE
Uncaught TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by infomaniac50** [Ecwid/ecwid-wordpress-plugin#203]
On our website we have a constant contact signup form that uses Google's ReCaptcha API. The ReCaptcha API loads "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js" and then later unloads this script. This causes an error at the following lines because parentNode is null. https://github.com/Ecwid/ecwid-wordpress-plugin/blob/944b9db2ee67c0894d64afd8f5e7f18a2d943cca/js/frontend.js#L94

If you check the parentNode before calling methods on it then you can avoid the issue. #202

**Comment by meteor-ec** [comment]
Hi @infomaniac50!
Thank you for your pull request! We'll include your change in the release 6.9.2.
