### ISSUE TITLE
	com.ecwid.skeleton.feature.http.wrappers.exception.ExceptionHandlerWrapper-670df6e

### ISSUE THREAD

**Issue by unifiedesystems** [Ecwid/ecwid-wordpress-plugin#220]
We are receiving this error (WP 5.4.2) after plugin installation, on the ec-store page.

HTTP ERROR 404 Not Found
URI: | /controlPanel/
STATUS: 404 
MESSAGE: Not Found
SERVLET: com.ecwid.skeleton.feature.http.wrappers.exception.ExceptionHandlerWrapper-670df6e

Only the Storefront page is accessible from WordPress. How do we resolve this?

![ecwid](https://user-images.githubusercontent.com/8980058/85231568-d3b0ed80-b3bd-11ea-8309-396552e40d3e.png)

**Comment by meteor-ec** [comment]
Hi @unifiedesystems , thanks for reporting it. We'll look in the issue.

**Comment by meteor-ec** [comment]
Hi, @unifiedesystems.
Can you say this problem repeats now?
Please send information about your Store ID and site URL on our email support@ecwid.com

**Comment by unifiedesystems** [comment]
Thank you. I ran the plugin update and all pages are quickly accessible. Much appreciation! 
On Tuesday, June 30, 2020 meteor-ec <reply@reply.github.com> wrote:



Hi, @unifiedesystems.
Can you say this problem repeats now?
Please send information about your Store ID and site URL on our email support@ecwid.com
