### ISSUE TITLE
media_buttons_context depreciated

### ISSUE THREAD

**Issue by DaWolfey** [Ecwid/ecwid-wordpress-plugin#221]
The action media_buttons_context is depreciated as of wordpress 3.5, which is throwing an exception in wordpress, which is being caught in my dev environment.

It's a really simple fix:
Change the two add_action to media_buttons from media_buttons_context
then in the add_editor_button functions, echo the result rather than return it.

**Comment by makfruit** [comment]
Hi @DaWolfey , thanks for reporting it. We'll look in the issue.

**Comment by meteor-ec** [comment]
Hi @DaWolfey, we fixed this issue.
