### ISSUE TITLE
Product Schema "Brand" - Invalid Object Type

### ISSUE THREAD

**Issue by CompKingCanada** [Ecwid/ecwid-wordpress-plugin#240]
This is a placeholder for an item previously reported to support@ecwid.com.

The Schema.Org markup changed Oct 1, 2021 for Brand markup.  Since then, ECWID has been failing Google Search Console Validation.  This needs to be updated to the current schema.org requirements.

**Comment by meteor-ec** [comment]
Hi,

This is Ilnur from Ecwid.

Thank you for your report! I'll look into this issue and I'll come back with an answer.

**Comment by CompKingCanada** [comment]
Any update on this?  Seems like it should be an obvious quick win...

**Comment by meteor-ec** [comment]
Thanks for waiting. We will reply as soon as possible after any changes.

**Comment by CompKingCanada** [comment]
Please elevate the priority of this request.  This error is now moved from a Yellow Warning to a Red Error and is highly impacting our product listings.  It has now been over a year since this change was implemented from Google.

**Comment by Hazel-Ecwid** [comment]
Hi! You are right, it is a very important issue and we are so sorry that you’re waiting for the fix for such a long time! This case is in progress now, our team is working on it. Will update you once the issue is resolved!

**Comment by meteor-ec** [comment]
Hi @CompKingCanada 

We've fixed this issue. Thanks for your help!
