### ISSUE TITLE
Roadmap to php 8.*?

### ISSUE THREAD

**Issue by bnjmnrsh** [Ecwid/ecwid-wordpress-plugin#264]
Hello,

I've a number of clients that use Ecwid on their Wordpress installs. We are trying to strategise how and when we upgrade some clients to php 8.1. Obviously WP itself has a long road to silence all the depreciation notices - but specifically what's Ecwid's roadmap look like?

**Comment by meteor-ec** [comment]
Hi @bnjmnrsh,

Thanks for your question! The plugin should work well with PHP 8.1. Regardless, I recommend testing websites on staging servers with PHP 8.1 and then changing the php version on the production server.

**Comment by meteor-ec** [comment]
Just before closing this issue: Our plugin works fine with PHP 8. Feel free to use it.

Regards,
