### ISSUE TITLE
PHP 8 deprecation error in trim function

### ISSUE THREAD

**Issue by tomodwyer** [Ecwid/ecwid-wordpress-plugin#265]
Trying to upgrade to PHP v8.1.x is giving the following deprecation error in the ECWID plugin:

```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in
[...]/wp-content/plugins/ecwid-shopping-cart/includes/class-ecwid-config.php on line 73
```

https://github.com/Ecwid/ecwid-wordpress-plugin/blob/535fa3abfdad7ec3c993c2c0239a7fbdfe83a963/includes/class-ecwid-config.php#L73

This is a behaviour change in PHP 8 ([source](https://www.php.net/manual/en/function.trim.php#128441)), suggested solution would be:

```php
$store_id = intval( trim($store_id ?? '') );
```

**Comment by meteor-ec** [comment]
Hi @tomodwyer 

We fixed this issue in version 6.12.

Thanks for your feedback!
