### ISSUE TITLE
ecwid-wordpress-plugin/includes/class-ecwid-integration-divibuilder.php

### ISSUE THREAD

**Issue by betterend** [Ecwid/ecwid-wordpress-plugin#8]
hi,

kindly i saw your php file for divi builder with Ecwid. Where should i place this file, and is it compatible with any theme?

Thank you

**Comment by vuvvn** [comment]
This file adds "Ecwid" builder element to Divi Builder with some basic configuration, and it is enabled by the plugin if it detects Divi Builder. As for compatibility, well, it should be compatible with any theme, but, you know, there are thousands of themes, and we can't test it with them all. Why do you ask? Do you have some issue with the Ecwid plugin and Divi Builder?
